export const COMPANYGET = "COMPANYGET";
export const COMPANYGET_SUCCES = "COMPANYGET_SUCCES";
export const COMPANYGET_DATA = "COMPANYGET_DATA";

export const COMPANYSET = "COMPANYSET";
export const COMPANYSET_SUCCES = "COMPANYSET_SUCCES";

export const COMPANYSLIST = "COMPANYSLIST";
export const COMPANYSLIST_SUCCES = "COMPANYSLIST_SUCCES";